### ISSUE TITLE
CSS - Style Footer with the Contact Us Elements

### ISSUE THREAD

**Issue by heirfanahmed** [heirfanahmed/mood-movies#28]

**Comment by DesislavaMetodieva** [comment]
User Story:

As a website user, I want the footer to have a responsive design so that the information is easily accessible and visually appealing on all devices, including desktop, tablet, and mobile.

Acceptance Criteria:

The footer should be displayed correctly on all screen sizes and resolutions.
The text and images in the footer should be resized and repositioned to fit the screen.
