### ISSUE TITLE
CSS - Style Search text and Search button

### ISSUE THREAD

**Issue by heirfanahmed** [heirfanahmed/mood-movies#33]

**Comment by DesislavaMetodieva** [comment]
User Story:

As a developer I want the design of the search button to be updated to match the provided UI design so that the website has a consistent and visually appealing look.

Acceptance Criteria:

The element should match the provided UI design in terms of color, size, shape, and text.
The element should be implemented on all pages where the button is used.
The element should be responsive and display correctly on all devices and screen sizes.
